# Generated by Django 5.0.6 on 2024-06-02 13:53

import tweets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=200, validators=[tweets.models.validate_content]),
        ),
    ]
